# Generated by Django 4.2 on 2023-11-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='dateForm',
            new_name='dateFrom',
        ),
    ]
